import tkinter as tk
from tkinter import filedialog
import pandas as pd
from tkinter import messagebox
root = tk.Tk()
root.withdraw()
import re
import csv


filepath = filedialog.askopenfilename(title = "Select A File", filetypes = [("csv files","*.csv")])
#print(filepath)

try:
    df = pd.read_csv(filepath)
    df = df.drop(["DEPARTURE DATE","DEPARTURE TIME","TOTAL"], axis = 1)

    df = df.loc[df["NAME"].str.contains(r"[20][2|1]\d[\-]\d\d\d\d\d[\-]MN-0", regex=True)]
    start,stop,step = 0, -3, 1
    df["ARRIVAL TIME"] = df["ARRIVAL TIME"].str.slice(start, stop, step)
    #print(df)
    df.to_csv("MobileData.csv", index=False)
    
except FileNotFoundError:
    pass
except KeyError:
    messagebox.showerror("Error", "*.csv file is invalid, make sure it is generated by the mobile")
except UnicodeDecodeError:
    messagebox.showerror("Error", "*.csv file is invalid, make sure it is generated by the mobile")

